spring:
  application:
    name: aep

  config:
    import: "optional:file:.env[.properties]"

  mongodb:
    uri: mongodb://${DB_ROOT_NAME}:${DB_ROOT_PASS}@localhost:${MONGO_PORT}/${DB_NAME}?authSource=admin
